COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_PRIV_INCLUDEDIRS := .
COMPONENT_SRCDIRS := .
COMPONENT_ADD_LDFLAGS := -Wl,--whole-archive -l$(COMPONENT_NAME) -Wl,--no-whole-archive
COMPONENT_REQUIRES := esp_dsp spiffs 